### GET all students
GET http://127.0.0.1:3000/api/students

### GET a single student by id
GET http://127.0.0.1:3000/api/students/8

### CREATE a new student
POST http://127.0.0.1:3000/api/students
Content-Type: application/json

{"first_name":"David","age":40}

### DELETE a student by id
DELETE http://127.0.0.1:3000/api/students/2
